In [10]:
import numpy as np


def initialize_matrices():
    # Initialize the I matrix (4x5)
    I = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])

    # Initialize the W matrix (5x6)
    W = np.array([[21, 22, 23, 24, 25, 26],
                  [27, 28, 29, 30, 31, 32],
                  [33, 34, 35, 36, 37, 38],
                  [39, 40, 41, 42, 43, 44],
                  [45, 46, 47, 48, 49, 50]])

    # Initialize the O matrix (4x6) with zeros
    O = np.zeros((4, 6))

    return I, W, O

def matrix_multiply(I, W, O):
    # Perform the matrix multiplication to populate O
    for b in range(4):
        for k in range(6):
            for c in range(5):
                # Calculate the product of I[b][c] and W[c][k]
                a = I[b][c] * W[c][k]

                # Print the intermediate values
                print(f"Multiplying I[{b}][{c}] = {I[b][c]} * W[{c}][{k}] = {W[c][k]} -> {a}")

                # Add the product to the result matrix O
                O[b][k] += a

                # Print the updated value of O[b][k]
                print(f"Updated O[{b}][{k}] = {O[b][k]}")
    
    return O

In [11]:
# Initialize matrices
I, W, O = initialize_matrices()

# Perform matrix multiplication
O_matrix = matrix_multiply(I, W, O)


Multiplying I[0][0] = 1 * W[0][0] = 21 -> 21
Updated O[0][0] = 21.0
Multiplying I[0][1] = 2 * W[1][0] = 27 -> 54
Updated O[0][0] = 75.0
Multiplying I[0][2] = 3 * W[2][0] = 33 -> 99
Updated O[0][0] = 174.0
Multiplying I[0][3] = 4 * W[3][0] = 39 -> 156
Updated O[0][0] = 330.0
Multiplying I[0][4] = 5 * W[4][0] = 45 -> 225
Updated O[0][0] = 555.0
Multiplying I[0][0] = 1 * W[0][1] = 22 -> 22
Updated O[0][1] = 22.0
Multiplying I[0][1] = 2 * W[1][1] = 28 -> 56
Updated O[0][1] = 78.0
Multiplying I[0][2] = 3 * W[2][1] = 34 -> 102
Updated O[0][1] = 180.0
Multiplying I[0][3] = 4 * W[3][1] = 40 -> 160
Updated O[0][1] = 340.0
Multiplying I[0][4] = 5 * W[4][1] = 46 -> 230
Updated O[0][1] = 570.0
Multiplying I[0][0] = 1 * W[0][2] = 23 -> 23
Updated O[0][2] = 23.0
Multiplying I[0][1] = 2 * W[1][2] = 29 -> 58
Updated O[0][2] = 81.0
Multiplying I[0][2] = 3 * W[2][2] = 35 -> 105
Updated O[0][2] = 186.0
Multiplying I[0][3] = 4 * W[3][2] = 41 -> 164
Updated O[0][2] = 350.0
Multiplying I[0][4] = 5 * W[4][2]

In [12]:

print("result of I[b][c]")
print(I)
print()

# Print the result matrix O
print("Result matrix O[B][K]:")
print(O_matrix)

result of I[b][c]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Result matrix O[B][K]:
[[ 555.  570.  585.  600.  615.  630.]
 [1380. 1420. 1460. 1500. 1540. 1580.]
 [2205. 2270. 2335. 2400. 2465. 2530.]
 [3030. 3120. 3210. 3300. 3390. 3480.]]
